import type {Metadata} from "next";
import {Gilda_Display, Roboto} from "next/font/google";
import "./globals.css";


// Настраиваем Gilda Display
const gilda = Gilda_Display({
    variable: "--font-gilda",
    subsets: ["latin"],
    weight: "400",
});

const roboto = Roboto({
    variable: "--font-roboto",
    subsets: ["latin"],
    weight: "400",
});

export const metadata: Metadata = {
    title: "ALNflowers",
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={`${gilda.variable} ${roboto.variable} antialiased`}>
        {children}
        </body>
        </html>
    );
}